FROM node:20-alpine AS build

WORKDIR /app
COPY package.json package-lock.json ./
COPY apps/api/package.json apps/api/package.json
COPY apps/web/package.json apps/web/package.json
RUN npm ci

COPY . .

ENV NODE_ENV=production
ENV NEXT_PUBLIC_API_URL=/api
ENV NEXT_PUBLIC_ROOT_DOMAIN=hubregional.com.br
ENV NEXT_PUBLIC_IPTV_PUBLIC_HOST=iptv.hubregional.com.br
ENV NEXT_PUBLIC_IPTV_TENANT_SUBDOMAIN=guiguiplay

RUN npm run build -w @delivery/web

FROM node:20-alpine AS runtime

WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000
ENV NEXT_PUBLIC_API_URL=/api
ENV NEXT_PUBLIC_ROOT_DOMAIN=hubregional.com.br
ENV NEXT_PUBLIC_IPTV_PUBLIC_HOST=iptv.hubregional.com.br
ENV NEXT_PUBLIC_IPTV_TENANT_SUBDOMAIN=guiguiplay
ENV API_SERVER_URL=http://b5jw6gbpa73ksnfc8flvrdto.62.171.165.253.sslip.io

COPY --from=build /app/package.json /app/package-lock.json ./
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/apps/web/package.json ./apps/web/package.json
COPY --from=build /app/apps/web/.next ./apps/web/.next
COPY --from=build /app/apps/web/public ./apps/web/public
COPY --from=build /app/apps/web/next.config.ts ./apps/web/next.config.ts

EXPOSE 3000

CMD ["npm", "run", "start", "-w", "@delivery/web"]
